const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const element = {addEventListener(){},style:{},textContent:''};
const listeners = {};
class Form {constructor(id, fields, elements={}){this.id=id;this.fields=fields;this.elements=elements;}}
const context = vm.createContext({console,crypto:require('node:crypto').webcrypto,Date,HTMLFormElement:Form,FormData:class{constructor(form){this.fields=form.fields;}get(key){return this.fields[key]??null;}has(key){return Object.hasOwn(this.fields,key);}},document:{querySelector(){return element;},addEventListener(type,callback){(listeners[type] ||= []).push(callback);}},window:{addEventListener(){}},location:{hash:''},setTimeout,clearTimeout});
let source=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');
source=source.slice(0,source.lastIndexOf('(async()=>'));
vm.runInContext(fs.readFileSync(path.join(__dirname,'exercise-library.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'motion.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'fitness.js'),'utf8'),context);
vm.runInContext(source,context);
const run = code => vm.runInContext(code,context);
async function submit(id,fields,elements={}){context.form=new Form(id,fields,elements);await run('submit({target:form,preventDefault(){}})');}
(async()=>{
  run("state=initial(); date='2026-10-07'; render=()=>{}; save=async()=>true; toast=message=>{globalThis.lastToast=message;}");
  assert.equal(run('state.profile.calories'),1800);
  assert.equal(run('state.profile.steps'),10000);
  assert.equal(run('Object.keys(exercises).length'),23);
  for(const date of ['2026-10-05','2026-10-07','2026-10-09']){
    const planned=run(`plan('${date}').ids`);
    assert.ok(planned.length>=4&&planned.length<=6);
    assert.ok(planned.every(id=>run(`Object.hasOwn(exercises,'${id}')`)));
  }
  run("globalThis.legacy=initial();delete legacy.profile.goalPreset;legacy.profile.calories=2000;legacy.profile.steps=8000;legacy.days['2026-10-06']={notes:'Keep this history'};");
  assert.equal(run('applyGoalPreset(legacy)'),true);
  assert.equal(run('legacy.profile.calories'),1800);
  assert.equal(run('legacy.profile.steps'),10000);
  assert.equal(run("legacy.days['2026-10-06'].notes"),'Keep this history');
  run('legacy.profile.calories=1900;');
  assert.equal(run('applyGoalPreset(legacy)'),false);
  assert.equal(run('legacy.profile.calories'),1900,'Later manual changes must not be overwritten');
  assert.equal(run('plan().training'),true);
  assert.equal(run("plan('2026-10-08').training"),false);
  assert.notEqual(run("plan('2026-10-07').name"),run("plan('2026-10-09').name"));
  await submit('profile-form',{name:'Benj',goal:'Build strength',weight:'75',height:'170',age:'35',calories:'2100',protein:'120',steps:'8000',water:'2000'});
  await submit('food-form',{name:'Lunch',meal:'Lunch',calories:'500',protein:'30',carbs:'50',fat:'20'});
  assert.equal(run('totals().calories'),500);
  await submit('cardio-form',{activity:'walk',minutes:'30',distance:'2',burn:'',effort:'Moderate'});
  assert.equal(run('totals().burn'),79);
  await submit('checkin',{weight:'74.5',sleep:'7',water:'1800',steps:'10000',notes:'Good session'});
  assert.equal(run('totals().burn'),79,'Steps must not count calories twice');
  assert.equal(run('activeWeight()'),74.5);
  const walkingPreview=run("caloriePreview('cardio',{activity:'walk',minutes:30,burn:''}).value");
  assert.equal(walkingPreview,78);
  assert.equal(run("caloriePreview('cardio',{activity:'walk',minutes:60,burn:''}).value"),156);
  assert.ok(run("caloriePreview('cardio',{activity:'jog',minutes:30,burn:''}).value")>walkingPreview);
  assert.equal(run("caloriePreview('cardio',{activity:'jog',minutes:30,burn:'0'}).value"),0,'Explicit zero is an override');
  assert.equal(run("caloriePreview('resistance',{minutes:45,burn:''}).value"),147);
  run("globalThis.oldDate=date;date='2026-10-01';state.profile.weight='';");
  assert.equal(run("caloriePreview('cardio',{activity:'walk',minutes:30,burn:''}).value"),null);
  assert.equal(run("caloriePreview('resistance',{minutes:45,burn:'120'}).value"),120);
  run("date=oldDate;state.profile.weight=75;");
  const id=run('plan().ids[0]');
  await submit('workout-form',{minutes:'45',burn:'100',notes:'',warmup:'on',cooldown:'on',[`${id}-0-weight`]:'10',[`${id}-0-reps`]:'10',[`${id}-0-done`]:'on'},{[`${id}-0-weight`]:{}});
  assert.equal(run('day().workout.burn'),100);
  assert.equal(run('totals().burn'),179);
  assert.equal(run('day().workout.sets[plan().ids[0]][0].done'),true);
  // Round-trip a real populated journal through the import validator.
  assert.equal(run('validateBackup(JSON.parse(JSON.stringify(state))).profile.name'),'Benj');
  assert.throws(()=>run('validateBackup({version:1,profile:{},days:{}})'));
  const before=run('day().workout.minutes');
  await submit('workout-form',{minutes:'60',burn:'100',notes:'',[`${id}-0-weight`]:'10',[`${id}-0-reps`]:'',[`${id}-0-done`]:'on'},{[`${id}-0-weight`]:{}});
  assert.equal(run('day().workout.minutes'),before,'Incomplete checked sets must not replace a saved workout');
  for(const page of ['overview','foodPage','cardioPage','resistancePage','fitnessPage','progressPage','profilePage'])assert.ok(run(`${page}()`).length>100);
  assert.ok(run('fitnessPage()').includes('id="exercise-picker"'),'Mobile fitness needs an exercise picker');
  for(const id of require('./motion.js').ids){
    const svg=run(`Fitness.svg('${id}')`);
    assert.ok(svg.includes('<animate '),`${id} needs animated movement`);
    assert.ok(!svg.includes('NaN')&&!svg.includes('undefined'),`${id} needs valid coordinates`);
    assert.ok(run(`Fitness.guide('${id}',exercises)`).includes('movement-toggle'));
  }
  assert.ok(run("exerciseHTML('carry',null)").includes('SECONDS'));
  assert.ok(run("exerciseHTML('curl',null)").includes('REPS'));
  assert.ok(run("exerciseOptions(['curl'])").includes('hammer'));
  assert.ok(!run("exerciseOptions(['curl'])").includes('value="curl"'));
  run("workoutDrafts[date]={type:'Custom resistance',ids:['carry'],sets:{carry:defaultSets('carry')},minutes:30};");
  await submit('workout-form',{minutes:'30',burn:'',notes:'Carry session','carry-0-weight':'12','carry-0-reps':'40','carry-0-done':'on'},{'carry-0-weight':{}});
  assert.equal(run('day().workout.sets.carry[0].reps'),'40');
  assert.equal(run('day().workout.sets.carry[0].weight'),'12');
  assert.equal(run('workoutDrafts[date]'),undefined);
  assert.equal(run('validateBackup(JSON.parse(JSON.stringify(state))).days[date].workout.ids[0]'),'carry');
  const attributes = {'aria-pressed':'false'};
  const animations = [{setAttribute(key,value){this[key]=value;}}];
  const animationSVG = {paused:false,pauseAnimations(){this.paused=true;},unpauseAnimations(){this.paused=false;},querySelectorAll(){return animations;},setCurrentTime(value){this.time=value;}};
  const playButton = {getAttribute(key){return attributes[key];},setAttribute(key,value){attributes[key]=value;},closest(){return guide;}};
  const playState={}, speedOutput={};
  const guide={querySelector(selector){return {'svg':animationSVG,'.movement-toggle':playButton,'.movement-state':playState,'.movement-speed-value':speedOutput}[selector];}};
  const playEvent={target:{closest(selector){return selector==='.movement-toggle'?playButton:null;}}};
  listeners.click[0](playEvent);
  assert.equal(animationSVG.paused,true);
  assert.equal(playState.textContent,'Paused');
  listeners.click[0](playEvent);
  assert.equal(animationSVG.paused,false);
  listeners.input[0]({target:{matches(selector){return selector==='.movement-speed';},closest(){return guide;},value:'0.5'}});
  assert.equal(animations[0].dur,'8s');
  assert.equal(animationSVG.time,0);
  context.animationRoot={querySelectorAll(){return [guide];}};
  context.window.matchMedia=()=>({matches:true});
  run('Fitness.mount(animationRoot)');
  assert.equal(animationSVG.paused,true,'Reduced motion should initially pause playback');
  assert.equal(run("escapeHTML('<img onerror=alert(1)>')"),'&lt;img onerror=alert(1)&gt;');
  // Exercise the actual save function with transaction completion and failure.
  vm.runInContext(source.match(/async function save\(\)\{[\s\S]*?(?=\nfunction toast)/)[0],context);
  run("db={transaction(){const tx={objectStore(){return {put(data){globalThis.savedData=JSON.parse(JSON.stringify(data));setTimeout(()=>tx.oncomplete(),0);}}}};return tx;}}");
  assert.equal(await run('save()'),true);
  assert.equal(run('savedData.days[date].food[0].calories'),500);
  run("db={transaction(){throw new Error('Storage full');}}");
  assert.equal(await run('save()'),false);
  console.log('PASS: 23 exercise entries, updated plans, timed tracking, backup round-trip, 25 guides, playback, calories, journal saves.');
})().catch(error=>{console.error(error);process.exitCode=1;});
